// === LEVELS DEFINITIONS ===
// TODOs 7, 11, and 12 will require changes to this section
const LEVELS = [
  {
    name: "Level 1",
    speed: 3,
    gameObjects: [
      { type: "obstacle", kind: "spikes", x: 980, y: groundY - 120, contactScoreChange: -40 },
      { type: "obstacle", kind: "spikes", x: 1750, height: 10, width: 20, y: groundY, contactScoreChange: -40},
      { type: "obstacle", kind: "spikes", x: 250, y: groundY, contactScoreChange: -40},

      { type: "enemy", kind: "bug", x: 1650, y: groundY, hp: 1, contactHealthChange: -30, contactScoreChange: -50 },
      { type: "enemy", kind: "bug", x: 1850, y: groundY, hp: 3, contactHealthChange: -30, contactScoreChange: -50 },
      { type: "enemy", kind: "bug", x: 1150, y: groundY - 140, hp: 1, contactHealthChange: -30, contactScoreChange: -50 },

      { type: "powerup", kind: "healthUp", x: 1400, y: groundY - 50, contactHealthChange: + 30, contactScoreChange: 50},
      { type: "powerup", kind: "healthUp", x: 1250, y: groundY - 150, contactHealthChange: + 30, contactScoreChange: 50},

      { type: "platform", kind: "basicPlatform", x: 1150, y: groundY - 100, contactHealthChange: -5},
      { type: "platform", kind: "basicPlatform", x: 1400, y: groundY - 180, width: 500, height: 50, contactHealthChange: -10 },
      { type: "platform", kind: "basicPlatform", x: 650, y: groundY - 65, contactHealthChange: 0},
      { type: "platform", kind: "basicPlatform", x: 900,  y: groundY - 80, hp: 10},
      { type: "platform", kind: "basicPlatform", width: 100, height: 900, x: 50, y:groundY - 100, contactHealthChange: - 30},

      { type: "goal", kind: "flag", x: 2000, y: groundY },
    ],
  },
  {
    name: "Level 2",
    speed: 4,
    gameObjects: [
      { type: "obstacle", kind: "spikes", x: 800, y: groundY, contactScoreChange: -40},
      { type: "obstacle", kind: "spikes", x: 1200, y: groundY, contactScoreChange: -40},
      { type: "obstacle", kind: "spikes", x: 1400, y: groundY, contactScoreChange: -40},
      { type: "obstacle", kind: "spikes", x: 2200, y: groundY, contactScoreChange: -40},
      { type: "obstacle", kind: "spikes", x: 2300, y: groundY, contactScoreChange: -40},

      { type: "enemy", kind: "bug", x: 400, y: groundY, contactHealthChange: -30, contactScoreChange: -50, hp: 1},
      { type: "enemy", kind: "bug", x: 600, y: groundY, contactHealthChange: -30, contactScoreChange: -50, hp: 1},
      { type: "enemy", kind: "bug", x: 1600, y: groundY, contactHealthChange: -30, contactScoreChange: -50, hp: 1  },
      { type: "enemy", kind: "bug", x: 1900, y: groundY, contactHealthChange: -30, contactScoreChange: -50, hp: 1  },
      { type: "enemy", kind: "bug", x: 2000, y: groundY - 100, contactHealthChange: -30, contactScoreChange: -50, hp: 1 },

      { type: "powerup", kind: "healthUp", x: 1600, y: groundY - 250, contactHealthChange: 30, contactScoreChange: 50 },
      { type: "powerup", kind: "healthUp", x: 100, y: groundY - 100, contactHealthChange: 30, contactScoreChange: 50 },
      { type: "powerup", kind: "healthUp", x: 900, y: groundY, contactHealthChange: 30, contactScoreChange: 50 },

      { type: "platform", kind: "basicPlatform", x: 1000, y: groundY, width: 10, height: 100, contactHealthChange: -5},
      { type: "platform", kind: "basicPlatform", x: 1000, y: groundY - 400, width: 10, height: -200 },
      { type: "platform", kind: "basicPlatform", x: 1500, y: groundY, width: 10, height: 100, contactHealthChange: -10},
      { type: "platform", kind: "basicPlatform", x: 2000, y: groundY, width: 10, height: 100, hp: 0,},

      { type: "goal", kind: "flag", x: 2250, y: groundY },
    ],
  },
   {
    name: "Level 3: Have Fun :3",
    speed: 9,
    gameObjects: [
      { type: "obstacle", kind: "spikes", x: 4500, y: groundY - 140, contactScoreChange: -40},
      { type: "obstacle", kind: "spikes", x: 5200, y: groundY - 140, contactScoreChange: -40},
      { type: "obstacle", kind: "spikes", x: 5300, y: groundY - 140, contactScoreChange: -40},
      { type: "obstacle", kind: "spikes", x: 6000, y: groundY - 150, contactScoreChange: -40},
      { type: "obstacle", kind: "spikes", x: 6500, y: groundY - 140, contactScoreChange: -40},
      { type: "obstacle", kind: "spikes", x: 7300, y: groundY - 140, contactScoreChange: -40},
      { type: "obstacle", kind: "spikes", x: 7400, y: groundY - 140, contactScoreChange: -40},
      { type: "obstacle", kind: "spikes", x: 7500, y: groundY - 140, contactScoreChange: -40},
      { type: "obstacle", kind: "spikes", x: 8000, y: groundY - 170, contactScoreChange: -40},
      { type: "obstacle", kind: "spikes", x: 8200, y: groundY - 140, contactScoreChange: -40},

      { type: "enemy", kind: "bug", x: 1200, y: groundY, contactHealthChange: -30, contactScoreChange: -50, hp: 1},
      { type: "enemy", kind: "bug", x: 1500, y: groundY, contactHealthChange: -30, contactScoreChange: -50, hp: 2},
      { type: "enemy", kind: "bug", x: 1600, y: groundY - 15, contactHealthChange: -30, contactScoreChange: -50, hp: 1 },
      { type: "enemy", kind: "bug", x: 1900, y: groundY, contactHealthChange: -30, contactScoreChange: -50, hp: 1},
      { type: "enemy", kind: "bug", x: 2000, y: groundY - 100, contactHealthChange: -30, contactScoreChange: -50, hp: 1},
      { type: "enemy", kind: "bug", x: 3000, y: groundY, contactHealthChange: -30, contactScoreChange: -50, hp: 2},
      { type: "enemy", kind: "bug", x: 3500, y: groundY - 5, contactHealthChange: -30, contactScoreChange: -50, hp: 2},
      { type: "enemy", kind: "bug", x: 4000, y: groundY, contactHealthChange: -30, contactScoreChange: -50, hp: 1},
      { type: "enemy", kind: "bug", x: 5000, y: groundY - 10, contactHealthChange: -30, contactScoreChange: -50, hp: 1},
      { type: "enemy", kind: "bug", x: 5300, y: groundY - 100, contactHealthChange: -30, contactScoreChange: -50, hp: 2 },
      { type: "enemy", kind: "bug", x: 6000, y: groundY, contactHealthChange: -30, contactScoreChange: -50, hp: 1},
      { type: "enemy", kind: "bug", x: 7000, y: groundY, contactHealthChange: -30, contactScoreChange: -50, hp: 2},
      { type: "enemy", kind: "bug", x: 8200, y: groundY - 15, contactHealthChange: -30, contactScoreChange: -50, hp: 1 },
      { type: "enemy", kind: "bug", x: 8300, y: groundY, contactHealthChange: -30, contactScoreChange: -50, hp: 1  },
      { type: "enemy", kind: "bug", x: 9000, y: groundY - 100, contactHealthChange: -30, contactScoreChange: -50, hp: 2 },
      { type: "enemy", kind: "bug", x: 9600, y: groundY, contactHealthChange: -30, contactScoreChange: -50, hp: 1},
      { type: "enemy", kind: "bug", x: 9750, y: groundY - 5, contactHealthChange: -30, contactScoreChange: -50, hp: 2},
      { type: "enemy", kind: "bug", x: 10000, y: groundY, contactHealthChange: -30, contactScoreChange: -50, hp: 1  },
      { type: "enemy", kind: "bug", x: 11000, y: groundY - 10, contactHealthChange: -30, contactScoreChange: -50, hp: 1  },
      { type: "enemy", kind: "bug", x: 12000, y: groundY - 100, contactHealthChange: -30, contactScoreChange: -50, hp: 2 },

      { type: "powerup", kind: "healthUp", x: 1600, y: groundY, contactHealthChange: 30, contactScoreChange: 50 },
      { type: "powerup", kind: "healthUp", x: 1000, y: groundY - 100, contactHealthChange: 30, contactScoreChange: 50 },
      { type: "powerup", kind: "healthUp", x: 200, y: groundY, contactHealthChange: 30, contactScoreChange: 50 },
      { type: "powerup", kind: "healthUp", x: 7000, y: groundY, contactHealthChange: 30, contactScoreChange: 50 },
      { type: "powerup", kind: "healthUp", x: 7000, y: groundY - 130, contactHealthChange: 30, contactScoreChange: 50 },

      { type: "platform", kind: "basicPlatform", x: 3000, y: groundY - 100, width: 100, height: 40, contactHealthChange: -5},
      { type: "platform", kind: "basicPlatform", x: 3100, y: groundY - 105, width: 200, height:40 },
      { type: "platform", kind: "basicPlatform", x: 3300, y: groundY - 115, width: 300, height: 40, contactHealthChange: -10},
      { type: "platform", kind: "basicPlatform", x: 3600, y: groundY - 130, width: 500, height: 40, hp: 0,},
      { type: "platform", kind: "basicPlatform", x: 4100, y: groundY - 130, width: 7000, height: 40, hp: 0,},
        { type: "platform", kind: "basicPlatform", x: 5000, y: groundY - 200, width: 10, height: 50, hp: 0,},
        { type: "platform", kind: "basicPlatform", x: 8000, y: groundY - 210, width: 10, height: 50, hp: 0,},
        { type: "platform", kind: "basicPlatform", x: 9000, y: groundY - 200, width: 10, height: 50, hp: 0, contactHealthChange: -20},

      { type: "goal", kind: "flag", x: 12250, y: groundY },
    ],
  },
];

let currentLevel = LEVELS[0];
let currentLevelIndex = 0;
// === END LEVELS DEFINITIONS ===

// === DEFAULT VALUES FOR EACH "type" AND "kind" OF OBJECT (STUDENT-EDITABLE) ===
const DEFAULT_VALUES = {
  obstacle: {
    spikes: {
      imageUrl: "images/interactable/spikes.png",
      width: 48,
      height: 48,
      hitWidth: 40,
      hitHeight: 44,
      speedX: 0,
      speedY: 0,
      minY: 0,
      maxY: 0,
      contactHealthChange: -20,
      contactScoreChange: 0,
      projectileHealthChange: 0,
      projectileScoreChange: 0,
      hp: 0,
      collect: false,
    },
  },
  enemy: {
    bug: {
      imageUrl: "images/interactable/bug.png",
      width: 75,
      height: 75,
      hitWidth: 75,
      hitHeight: 75,
      speedX: 0,
      speedY: 0,
      minY: 0,
      maxY: groundY - 75,
      contactHealthChange: -30,
      contactScoreChange: 0,
      projectileHealthChange: 0,
      projectileScoreChange: 50,
      hp: 3,
      collect: false,
    },
  },
  powerup: {
    healthUp: {
      imageUrl: "images/interactable/health-up.png",
      width: 32,
      height: 32,
      hitWidth: 32,
      hitHeight: 32,
      speedX: 0,
      speedY: 0,
      minY: 0,
      maxY: groundY - 32,
      contactHealthChange: +20,
      contactScoreChange: 0,
      projectileHealthChange: 0,
      projectileScoreChange: 0,
      hp: 0,
      collect: true,
    },
  },
  goal: {
    flag: {
      imageUrl: "images/interactable/flag.png",
      width: 100,
      height: 100,
      hitWidth: 100,
      hitHeight: 100,
      speedX: 0,
      speedY: 0,
      minY: 0,
      maxY: 0,
      contactHealthChange: 0,
      contactScoreChange: +100,
      projectileHealthChange: 0,
      projectileScoreChange: 0,
      hp: 0,
      collect: true,
    },
  },
  platform: {
    basicPlatform: {
      imageUrl: "images/interactable/basic-platform.png",
      width: 200,
      height: 50,
      hitWidth: 200,
      hitHeight: 50,
      speedX: 0,
      speedY: 0,
      minY: 0,
      maxY: groundY - 50,
      contactHealthChange: 0,
      contactScoreChange: 0,
      projectileHealthChange: 0,
      projectileScoreChange: 0,
      hp: Infinity,
      collect: false,
    },
  },
};
// === END DEFAULT VALUES ===
